# Generated by Django 4.2.2 on 2023-07-13 14:10

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_ky', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('title_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('title_ky', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('body', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('body_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('body_ky', ckeditor.fields.RichTextField(null=True, verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('image', models.ImageField(upload_to='news', verbose_name='Изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('-date',),
            },
        ),
    ]
