# Generated by Django 4.2.2 on 2023-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercontactinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserEmail',
        ),
        migrations.DeleteModel(
            name='UserContactInfo',
        ),
    ]
